#!/usr/bin/env bash
set -e

SOURCE="$0"
while [ -L "$SOURCE" ]; do
    SOURCE="$(readlink $SOURCE)"
done
LICENSE_DIR="${LICENSE_DIR:-$(dirname $SOURCE)/licenses/}"

list_licenses() {
    echo $(ls $LICENSE_DIR)
}

show_usage() {
    echo "Usage: $0 <license>"
    echo "Available licenses: $(list_licenses)"
}

lowercase() {
    echo "$*" | tr '[A-Z]' '[a-z]'
}

find_license() {
    input=$1
    for license in $(list_licenses); do
        if [ "$(lowercase $license)" = "$input" ]; then
            echo $license
            return
        fi
    done
}

confirm_overwrite() {
    name=$1
    read -p "\"$name\" file already exists. Overwrite? [N/y] " -n 1 reply
    echo
    if [ "$(lowercase $reply)" != "y" ]; then
        echo "Aborted."
        exit 1
    fi
}

add_license() {
    file=$1
    year=$(date +"%Y")
    author=$(git config user.name)
    if [ -f LICENSE ]; then
        confirm_overwrite LICENSE
    fi
    cat $file | sed "s/{{year}}/$year/" | sed "s/{{author}}/$author/" > LICENSE
}

main() {
    input=$1
    if [ -n "$input" ]; then
        filename="$(find_license $input)"
        file="$LICENSE_DIR/$filename"
        if [ -f "$file" ]; then
            add_license $file
            echo "Wrote $filename license to LICENSE."
        else
            echo "\"$input\" is not an available license."
            echo "Available licenses are: $(list_licenses)"
            exit 1
        fi
    else
        show_usage
        exit 1
    fi
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main "$@"
fi
